runtime: perl516

# belden's fingers want to type this, let's make life easy for him
prove: |
  if [[ -n "${ROCK_ARGS}" ]]; then
    TEST_AUTHOR=1 exec prove ${PERL_TEST_INC} -r -l -v ${ROCK_ARGS}
  else
    TEST_AUTHOR=1 exec prove ${PERL_TEST_INC} -r -l -v t
  fi

